In [ ]:
import sys, os

# Path to the folder that *contains* the digimat_scripts package
sys.path.append(r"D:\harryhz\Documents")

# or, if digimat_scripts is the root and you import as a top-level package:

import add_fiber_orientation as afo
from digimat_scripts.script_utils import change_extension
import numpy as np

### Generate RVEs

#### Single Template

In [ ]:
import singleTemplate
template_file_name = "FPM14-nolayers"
new_daf_name = template_file_name
num_samples = 5
template_directory = r"Y:\Students\Zhou_Harry\abaqus\template\FPM14"
temp_dir = r"D:\harryhz\Documents\abaqus\temp"
output_dir = r"Y:\Students\Zhou_Harry\abaqus\working"

singleTemplate.singleTemplate(template_file_name,new_daf_name,num_samples,template_directory,temp_dir,output_dir)

2026-06-25 11:05:47.803 | INFO     | singleTemplate:singleTemplate:51 - Created new directories
2026-06-25 11:05:47.818 | INFO     | singleTemplate:singleTemplate:58 - Copied Template daf file from Y:\Students\Zhou_Harry\abaqus\template\FPM14\FPM14-nolayers.daf to D:\harryhz\Documents\abaqus\temp\FPM14-nolayers\Template.daf
2026-06-25 11:05:47.822 | SUCCESS  | singleTemplate:singleTemplate:67 - Created new daf files based off template
Processing RVE Generation:   0%|          | 0/5 [00:00<?, ?it/s]

#### Multiple Templates

In [ ]:
import multiTemplate

template_directory = r"Y:\Students\Zhou_Harry\abaqus\template\FPM14"

job_name = "FPM14-layers"

num_samples = 5

temp_dir = r"D:\harryhz\Documents\abaqus\temp"
output_dir = r"Y:\Students\Zhou_Harry\abaqus\working"

multiTemplate.multiTemplate(template_directory,job_name,num_samples,temp_dir,output_dir)

### Check Fiber Orientation

In [4]:
input_path = r"Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers\digimat_out"

FOT_list = []
filenames = [f for f in os.listdir(input_path) if f.endswith(f".inp")]
for file in filenames:
    print(file)

    FOT_list.append(afo.check_fiber_orientation_tensor(input_filename=file[:-4], input_path=input_path))
actual_FOT = np.array([[ 0.79,0,0],
                       [0, 0.11,   0],
                       [ 0, 0, 0.1]])

for orientation in FOT_list:
    print(orientation)
    print(np.linalg.norm(orientation - actual_FOT, ord="fro"))
average_FOT = np.array(FOT_list).mean(axis=0)
print(average_FOT)

print(np.linalg.norm(average_FOT - actual_FOT, ord="fro"))

2026-06-25 10:22:01.214 | INFO     | digimat_scripts.dataio.abaqus.read_input_file:open_file:102 - Opened Abaqus input file: FPM14-nolayers_3.inp


FPM14-nolayers_3.inp


2026-06-25 10:22:02.200 | SUCCESS  | digimat_scripts.dataio.abaqus.read_input_file:cache_keywords:139 - Cache created successfully with the following keywords: ('Elset',)
2026-06-25 10:22:02.202 | INFO     | digimat_scripts.dataio.abaqus.read_input_file:open_file:102 - Opened Abaqus input file: FPM14-nolayers_3.inp
2026-06-25 10:22:02.436 | SUCCESS  | digimat_scripts.dataio.abaqus.read_input_file:cache_keywords:139 - Cache created successfully with the following keywords: ('Elset',)
2026-06-25 10:22:02.451 | INFO     | digimat_scripts.dataio.digimat.read_orientation:check_file:69 - Checking orientation file: DefaultJobName_FPM14-nolayers_3_Fiber_orientation.txt at path: Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers\digimat_out
2026-06-25 10:22:02.455 | SUCCESS  | digimat_scripts.dataio.digimat.read_orientation:check_file:83 - Orientation file DefaultJobName_FPM14-nolayers_3_Fiber_orientation.txt in Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers\digimat_out found and valida

FPM14-nolayers_2.inp


2026-06-25 10:22:03.456 | SUCCESS  | digimat_scripts.dataio.abaqus.read_input_file:cache_keywords:139 - Cache created successfully with the following keywords: ('Elset',)
2026-06-25 10:22:03.458 | INFO     | digimat_scripts.dataio.abaqus.read_input_file:open_file:102 - Opened Abaqus input file: FPM14-nolayers_2.inp
2026-06-25 10:22:03.695 | SUCCESS  | digimat_scripts.dataio.abaqus.read_input_file:cache_keywords:139 - Cache created successfully with the following keywords: ('Elset',)
2026-06-25 10:22:03.709 | INFO     | digimat_scripts.dataio.digimat.read_orientation:check_file:69 - Checking orientation file: DefaultJobName_FPM14-nolayers_2_Fiber_orientation.txt at path: Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers\digimat_out
2026-06-25 10:22:03.713 | SUCCESS  | digimat_scripts.dataio.digimat.read_orientation:check_file:83 - Orientation file DefaultJobName_FPM14-nolayers_2_Fiber_orientation.txt in Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers\digimat_out found and valida

FPM14-nolayers_1.inp


2026-06-25 10:22:05.010 | SUCCESS  | digimat_scripts.dataio.abaqus.read_input_file:cache_keywords:139 - Cache created successfully with the following keywords: ('Elset',)
2026-06-25 10:22:05.012 | INFO     | digimat_scripts.dataio.abaqus.read_input_file:open_file:102 - Opened Abaqus input file: FPM14-nolayers_1.inp
2026-06-25 10:22:05.239 | SUCCESS  | digimat_scripts.dataio.abaqus.read_input_file:cache_keywords:139 - Cache created successfully with the following keywords: ('Elset',)
2026-06-25 10:22:05.255 | INFO     | digimat_scripts.dataio.digimat.read_orientation:check_file:69 - Checking orientation file: DefaultJobName_FPM14-nolayers_1_Fiber_orientation.txt at path: Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers\digimat_out
2026-06-25 10:22:05.260 | SUCCESS  | digimat_scripts.dataio.digimat.read_orientation:check_file:83 - Orientation file DefaultJobName_FPM14-nolayers_1_Fiber_orientation.txt in Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers\digimat_out found and valida

FPM14-nolayers_0.inp


2026-06-25 10:22:06.237 | SUCCESS  | digimat_scripts.dataio.abaqus.read_input_file:cache_keywords:139 - Cache created successfully with the following keywords: ('Elset',)
2026-06-25 10:22:06.239 | INFO     | digimat_scripts.dataio.abaqus.read_input_file:open_file:102 - Opened Abaqus input file: FPM14-nolayers_0.inp
2026-06-25 10:22:06.464 | SUCCESS  | digimat_scripts.dataio.abaqus.read_input_file:cache_keywords:139 - Cache created successfully with the following keywords: ('Elset',)
2026-06-25 10:22:06.479 | INFO     | digimat_scripts.dataio.digimat.read_orientation:check_file:69 - Checking orientation file: DefaultJobName_FPM14-nolayers_0_Fiber_orientation.txt at path: Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers\digimat_out
2026-06-25 10:22:06.483 | SUCCESS  | digimat_scripts.dataio.digimat.read_orientation:check_file:83 - Orientation file DefaultJobName_FPM14-nolayers_0_Fiber_orientation.txt in Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers\digimat_out found and valida

FPM14-nolayers_4.inp


2026-06-25 10:22:07.773 | SUCCESS  | digimat_scripts.dataio.abaqus.read_input_file:cache_keywords:139 - Cache created successfully with the following keywords: ('Elset',)
2026-06-25 10:22:07.775 | INFO     | digimat_scripts.dataio.abaqus.read_input_file:open_file:102 - Opened Abaqus input file: FPM14-nolayers_4.inp
2026-06-25 10:22:08.009 | SUCCESS  | digimat_scripts.dataio.abaqus.read_input_file:cache_keywords:139 - Cache created successfully with the following keywords: ('Elset',)
2026-06-25 10:22:08.023 | INFO     | digimat_scripts.dataio.digimat.read_orientation:check_file:69 - Checking orientation file: DefaultJobName_FPM14-nolayers_4_Fiber_orientation.txt at path: Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers\digimat_out
2026-06-25 10:22:08.027 | SUCCESS  | digimat_scripts.dataio.digimat.read_orientation:check_file:83 - Orientation file DefaultJobName_FPM14-nolayers_4_Fiber_orientation.txt in Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers\digimat_out found and valida

[[ 0.73763824 -0.00361224 -0.00536002]
 [-0.00361224  0.24253044 -0.00185134]
 [-0.00536002 -0.00185134  0.01983131]]
0.16377882039686106
[[0.76941828 0.00599807 0.01398552]
 [0.00599807 0.21352243 0.00131747]
 [0.01398552 0.00131747 0.01705929]]
0.13596424903311616
[[ 0.73588029  0.02968316 -0.00734395]
 [ 0.02968316  0.25030714  0.00621558]
 [-0.00734395  0.00621558  0.01381257]]
0.17885923017068475
[[ 0.75331942  0.00479367  0.00564895]
 [ 0.00479367  0.23528657 -0.00625097]
 [ 0.00564895 -0.00625097  0.01139401]]
0.15837026808254318
[[ 0.69687179 -0.00545287 -0.00655114]
 [-0.00545287  0.28221196 -0.0025869 ]
 [-0.00655114 -0.0025869   0.02091625]]
0.21152481893196534
[[ 7.38625602e-01  6.28196051e-03  7.58722033e-05]
 [ 6.28196051e-03  2.44771710e-01 -6.31230707e-04]
 [ 7.58722033e-05 -6.31230707e-04  1.66026874e-02]]
0.16684600328853988


### Add Fiber Orientation

In [11]:
input_path = r"Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers\digimat_out"
output_path = r"Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers\abaqus_inp"

afo.batched_run(
    input_path=input_path,   
    output_path= output_path,
    extension_type="inp",
    break_point="STEP",
)
change_extension.batch(path=output_path, old_extension="inp", new_extension="inc")

2026-06-24 15:32:17.936 | INFO     | digimat_scripts.dataio.abaqus.read_input_file:open_file:102 - Opened Abaqus input file: FPM14-nolayers_3.inp
2026-06-24 15:32:19.262 | SUCCESS  | digimat_scripts.dataio.abaqus.read_input_file:cache_keywords:139 - Cache created successfully with the following keywords: ('Elset',)
2026-06-24 15:32:19.309 | INFO     | digimat_scripts.dataio.digimat.read_orientation:check_file:69 - Checking orientation file: DefaultJobName_FPM14-nolayers_3_Fiber_orientation.txt at path: Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers\digimat_out
2026-06-24 15:32:19.312 | SUCCESS  | digimat_scripts.dataio.digimat.read_orientation:check_file:83 - Orientation file DefaultJobName_FPM14-nolayers_3_Fiber_orientation.txt in Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers\digimat_out found and validated.
2026-06-24 15:32:19.312 | INFO     | digimat_scripts.dataio.digimat.read_orientation:get_csv:100 - Reading orientation file: DefaultJobName_FPM14-nolayers_3_Fiber_ori