In [2]:
import sys, os

# Path to the folder that *contains* the digimat_scripts package
sys.path.append(r"D:\harryhz\Documents")

# or, if digimat_scripts is the root and you import as a top-level package:

import add_fiber_orientation as afo
from digimat_scripts.script_utils import change_extension
import numpy as np

### Generate RVEs

#### Single Template

In [ ]:
import singleTemplate
template_file_name = "FPM14-nolayers_V3"
new_daf_name = template_file_name
num_samples = 5
template_directory = r"Y:\Students\Zhou_Harry\abaqus\template\FPM14"
temp_dir = r"D:\harryhz\Documents\abaqus\temp"
output_dir = r"Y:\Students\Zhou_Harry\abaqus\working"

singleTemplate.singleTemplate(template_file_name,new_daf_name,num_samples,template_directory,temp_dir,output_dir)

2026-08-17 12:42:49.938 | INFO     | singleTemplate:singleTemplate:51 - Created new directories
2026-08-17 12:42:49.954 | INFO     | singleTemplate:singleTemplate:58 - Copied Template daf file from Y:\Students\Zhou_Harry\abaqus\template\FPM14\FPM14-nolayers_V3.daf to D:\harryhz\Documents\abaqus\temp\FPM14-nolayers_V3\Template.daf
2026-08-17 12:42:49.959 | SUCCESS  | singleTemplate:singleTemplate:67 - Created new daf files based off template
Processing RVE Generation:  60%|██████    | 3/5 [33:50<22:44, 682.47s/it]

#### Multiple Templates

In [ ]:
import multiTemplate

template_directory = r"Y:\Students\Zhou_Harry\abaqus\template\FPM14"

job_name = "FPM14-layers"

num_samples = 5

temp_dir = r"D:\harryhz\Documents\abaqus\temp"
output_dir = r"Y:\Students\Zhou_Harry\abaqus\working"

multiTemplate.multiTemplate(template_directory,job_name,num_samples,temp_dir,output_dir)

### Check Fiber Orientation

In [ ]:
input_path = r"Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers_V3\digimat_out"

FOT_list = []
filenames = [f for f in os.listdir(input_path) if f.endswith(f".inp")]
for file in filenames:
    print(file)

    FOT_list.append(afo.check_fiber_orientation_tensor(input_filename=file[:-4], input_path=input_path))
    print(afo.check_fiber_orientation_tensor(input_filename=file[:-4], input_path=input_path))
actual_FOT = np.array([[0.68,  -0.07, -0.16],
                      [-0.07,  0.25,   0.02],
                      [-0.16,  0.02,   0.07]])

for orientation in FOT_list:
    print(orientation)
    print(np.linalg.norm(orientation - actual_FOT, ord="fro"))
average_FOT = np.array(FOT_list).mean(axis=0)
print(average_FOT)

print(np.linalg.norm(average_FOT - actual_FOT, ord="fro"))

2026-08-17 14:32:42.929 | INFO     | digimat_scripts.dataio.digimat.read_orientation:check_file:69 - Checking orientation file: DefaultJobName_FPM14-nolayers_V3_1_Fiber_orientation.txt at path: Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers_V3\digimat_out


2026-08-17 14:32:42.932 | SUCCESS  | digimat_scripts.dataio.digimat.read_orientation:check_file:83 - Orientation file DefaultJobName_FPM14-nolayers_V3_1_Fiber_orientation.txt in Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers_V3\digimat_out found and validated.
2026-08-17 14:32:42.933 | INFO     | digimat_scripts.dataio.digimat.read_orientation:get_csv:100 - Reading orientation file: DefaultJobName_FPM14-nolayers_V3_1_Fiber_orientation.txt from path: Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers_V3\digimat_out
2026-08-17 14:32:42.937 | DEBUG    | digimat_scripts.dataio.digimat.read_orientation:get_csv:109 - Data shape: (412, 2)
2026-08-17 14:32:42.938 | SUCCESS  | digimat_scripts.dataio.digimat.read_orientation:get_csv:111 - Orientation data loaded from DefaultJobName_FPM14-nolayers_V3_1_Fiber_orientation.txt for phase Fiber
2026-08-17 14:32:42.950 | INFO     | digimat_scripts.dataio.digimat.read_orientation:check_file:69 - Checking orientation file: DefaultJobName_FPM14-no

FPM14-nolayers_V3_1.inp
[[ 0.68072527 -0.06726865 -0.16714271]
 [-0.06726865  0.25495478  0.01919942]
 [-0.16714271  0.01919942  0.06431995]]
FPM14-nolayers_V3_2.inp
[[ 0.71322986 -0.06081646 -0.15926564]
 [-0.06081646  0.23052778  0.00501653]
 [-0.15926564  0.00501653  0.05624236]]
FPM14-nolayers_V3_0.inp
[[ 0.67750033 -0.09232255 -0.17408606]
 [-0.09232255  0.26452983  0.03102693]
 [-0.17408606  0.03102693  0.05796984]]
[[ 0.68072527 -0.06726865 -0.16714271]
 [-0.06726865  0.25495478  0.01919942]
 [-0.16714271  0.01919942  0.06431995]]
0.01325057825367114
[[ 0.71322986 -0.06081646 -0.15926564]
 [-0.06081646  0.23052778  0.00501653]
 [-0.15926564  0.00501653  0.05624236]]
0.04786884065183747
[[ 0.67750033 -0.09232255 -0.17408606]
 [-0.09232255  0.26452983  0.03102693]
 [-0.17408606  0.03102693  0.05796984]]
0.04470685257963793
[[ 0.69048515 -0.07346922 -0.16683147]
 [-0.07346922  0.25000413  0.01841429]
 [-0.16683147  0.01841429  0.05951072]]
0.01850409135147264


In [ ]:
input_path = r"Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers_V2\digimat_out"

FOT_list = []
filenames = [f for f in os.listdir(input_path) if f.endswith(f".inp")]
for file in filenames:
    print(file)

    FOT_list.append(afo.check_fiber_orientation_tensor(input_filename=file[:-4], input_path=input_path, phase_name= "Voids"))
actual_FOT = np.array([[ 0.0305,0,0],
                       [0, 0.2390,   0],
                       [ 0, 0, 0.7304]])

for orientation in FOT_list:
    print(orientation)
    print(np.linalg.norm(orientation - actual_FOT, ord="fro"))
average_FOT = np.array(FOT_list).mean(axis=0)
print(average_FOT)

print(np.linalg.norm(average_FOT - actual_FOT, ord="fro"))

2026-08-05 15:35:27.736 | INFO     | digimat_scripts.dataio.digimat.read_orientation:check_file:69 - Checking orientation file: DefaultJobName_FPM14-nolayers_V2_3_Voids_orientation.txt at path: Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers_V2\digimat_out
2026-08-05 15:35:27.739 | SUCCESS  | digimat_scripts.dataio.digimat.read_orientation:check_file:83 - Orientation file DefaultJobName_FPM14-nolayers_V2_3_Voids_orientation.txt in Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers_V2\digimat_out found and validated.
2026-08-05 15:35:27.740 | INFO     | digimat_scripts.dataio.digimat.read_orientation:get_csv:100 - Reading orientation file: DefaultJobName_FPM14-nolayers_V2_3_Voids_orientation.txt from path: Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers_V2\digimat_out
2026-08-05 15:35:27.742 | DEBUG    | digimat_scripts.dataio.digimat.read_orientation:get_csv:109 - Data shape: (48, 2)
2026-08-05 15:35:27.742 | SUCCESS  | digimat_scripts.dataio.digimat.read_orientation:get_cs

FPM14-nolayers_V2_3.inp
FPM14-nolayers_V2_1.inp
FPM14-nolayers_V2_4.inp
FPM14-nolayers_V2_0.inp
FPM14-nolayers_V2_2.inp
[[ 0.010017   -0.00409576  0.02789731]
 [-0.00409576  0.36501608 -0.00624939]
 [ 0.02789731 -0.00624939  0.62496692]]
0.1705400846696471
[[ 0.00133557 -0.00172961  0.00177851]
 [-0.00172961  0.26871538 -0.05090849]
 [ 0.00177851 -0.05090849  0.72994905]]
0.08324318861936851
[[ 0.00915798 -0.01589427 -0.02941559]
 [-0.01589427  0.22224111 -0.01900839]
 [-0.02941559 -0.01900839  0.76860092]]
0.0717920652818231
[[ 0.01121119  0.0203842  -0.0318988 ]
 [ 0.0203842   0.28795639 -0.01667073]
 [-0.0318988  -0.01667073  0.70083242]]
0.08405327287250054
[[ 1.83742036e-02 -2.15010165e-02 -3.66170793e-03]
 [-2.15010165e-02  3.16122644e-01  5.45685410e-05]
 [-3.66170793e-03  5.45685410e-05  6.65503153e-01]]
0.1061034752618194
[[ 0.01001919 -0.00456729 -0.00706006]
 [-0.00456729  0.29201032 -0.01855649]
 [-0.00706006 -0.01855649  0.69797049]]
0.07149353928476954


### Add Fiber Orientation

In [ ]:
input_path = r"Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers_V3\digimat_out"
output_path = r"Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers_V3\abaqus_inp"

afo.batched_run(
    input_path=input_path,   
    output_path= output_path,
    extension_type="inp",
    break_point="STEP",
)
change_extension.batch(path=output_path, old_extension="inp", new_extension="inc")

2026-08-17 14:33:26.106 | INFO     | digimat_scripts.dataio.abaqus.read_input_file:open_file:102 - Opened Abaqus input file: FPM14-nolayers_V3_1.inp
2026-08-17 14:33:26.997 | SUCCESS  | digimat_scripts.dataio.abaqus.read_input_file:cache_keywords:139 - Cache created successfully with the following keywords: ('Elset',)
2026-08-17 14:33:27.012 | INFO     | digimat_scripts.dataio.digimat.read_orientation:check_file:69 - Checking orientation file: DefaultJobName_FPM14-nolayers_V3_1_Fiber_orientation.txt at path: Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers_V3\digimat_out
2026-08-17 14:33:27.016 | SUCCESS  | digimat_scripts.dataio.digimat.read_orientation:check_file:83 - Orientation file DefaultJobName_FPM14-nolayers_V3_1_Fiber_orientation.txt in Y:\Students\Zhou_Harry\abaqus\working\FPM14-nolayers_V3\digimat_out found and validated.
2026-08-17 14:33:27.016 | INFO     | digimat_scripts.dataio.digimat.read_orientation:get_csv:100 - Reading orientation file: DefaultJobName_FPM14-nolay

: 